CREATE DATABASE LOJA

USE LOJA

DROP DATABASE LOJA

--- CREATE DATABASE TESTE
--- USE TESTE
--- COMANDOS ACIMA PARA RESETAR O BANCO
--- PRECISAMOS RETIRAR ALGUNS NOT NULL'S

--- SELECT @@LANGUAGE AS 'Language Name'; 

CREATE TABLE CLIENTES(
	COD_CLI INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR (100) NOT NULL,
	DATA_NASC DATE NOT NULL,
	E_MAIL VARCHAR (100) 
)

GO
/* ALTER TABLE'S */
ALTER TABLE CLIENTES ADD CONSTRAINT PK_COD_CLI
PRIMARY KEY (COD_CLI)

GO


----------------------------------------------------------------------

CREATE TABLE TELEFONE_CLIENTES(
	COD_TEL_CLI INT NOT NULL IDENTITY(1,1),
	TIPO CHAR(3)NOT NULL,
	NUMERO VARCHAR (30) NOT NULL,
	FK_COD_CLI INT NOT NULL
)

GO
/* ALTER TABLE'S */
ALTER TABLE TELEFONE_CLIENTES ADD CONSTRAINT PK_COD_TEL_CLI
PRIMARY KEY (COD_TEL_CLI)
GO
ALTER TABLE TELEFONE_CLIENTES ADD CONSTRAINT FK_TEL_CLI
FOREIGN KEY (FK_COD_CLI)
REFERENCES CLIENTES(COD_CLI)
GO
ALTER TABLE TELEFONE_CLIENTES ADD CONSTRAINT CHECK_TEL_CLI_TIPO
CHECK (TIPO IN('RES','COM','CEL'))

GO

----------------------------------------------------------------------

CREATE TABLE ENDERECO_CLIENTES(
	COD_END_CLI INT NOT NULL IDENTITY(1,1),
	RUA VARCHAR (150) NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR (100) NOT NULL,
	CIDADE VARCHAR (100) NOT NULL,
	ESTADO CHAR (2) NOT NULL,
	FK_COD_CLI INT NOT NULL
)

GO
/* ALTER TABLE'S */
ALTER TABLE ENDERECO_CLIENTES ADD CONSTRAINT PK_COD_END_CLI
PRIMARY KEY (COD_END_CLI)
GO
ALTER TABLE ENDERECO_CLIENTES ADD CONSTRAINT FK_END_CLI
FOREIGN KEY (FK_COD_CLI)
REFERENCES CLIENTES(COD_CLI)
GO
ALTER TABLE ENDERECO_CLIENTES ADD CONSTRAINT UK_FK_END_COD_CLI UNIQUE(FK_COD_CLI)

GO


----------------------------------------------------------------------

CREATE TABLE DISTRIBUIDORES(
	COD_DIS INT NOT NULL IDENTITY(1,1),
	NOME_FANTASIA VARCHAR (100) NOT NULL,
	RAZAO_SOCIAL VARCHAR (100) NOT NULL,
	E_MAIL VARCHAR (100) NOT NULL
)

GO
/* ALTER TABLE'S */
ALTER TABLE DISTRIBUIDORES ADD CONSTRAINT PK_COD_DIS
PRIMARY KEY (COD_DIS)

GO


----------------------------------------------------------------------

CREATE TABLE TELEFONE_DISTRIBUIDORES(
	COD_TEL_DIS INT NOT NULL IDENTITY(1,1),
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR (30) NOT NULL,
	FK_COD_DIS INT NOT NULL
)
GO
/* ALTER TABLE'S */
ALTER TABLE TELEFONE_DISTRIBUIDORES ADD CONSTRAINT PK_COD_TEL_DIS
PRIMARY KEY (COD_TEL_DIS)
GO
ALTER TABLE TELEFONE_DISTRIBUIDORES ADD CONSTRAINT FK_TEL_DIS
FOREIGN KEY (FK_COD_DIS)
REFERENCES DISTRIBUIDORES(COD_DIS)
GO
ALTER TABLE TELEFONE_DISTRIBUIDORES ADD CONSTRAINT CHECK_TEL_DIS_TIPO
CHECK (TIPO IN('RES','COM','CEL'))

GO


----------------------------------------------------------------------

CREATE TABLE PRODUTOS(
	COD_PRO INT NOT NULL IDENTITY (1,1),
	DATA_VALIDADE DATE NOT NULL,
	DESCRICAO VARCHAR (150) NOT NULL,
	ESTOQUE INT NOT NULL,
	PRECO_CUSTO DECIMAL (10,2) NOT NULL,
	PRECO_VENDA DECIMAL (10,2) NOT NULL,
	FK_COD_DIS INT NOT NULL
)

GO
/* ALTER TABLE'S */
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_COD_PRO
PRIMARY KEY (COD_PRO)
GO
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRO_DIS
FOREIGN KEY (FK_COD_DIS)
REFERENCES DISTRIBUIDORES(COD_DIS)

GO


--- (EXERCÍCIO 2) SELECT * FROM PRODUTOS WHERE DATA_VALIDADE < (SELECT GETDATE())

----------------------------------------------------------------------

CREATE TABLE VENDAS(
	COD_VEN INT NOT NULL IDENTITY(1,1),
	DATA_VEN DATE NOT NULL,
	HORA TIME NOT NULL,
	TOTAL DECIMAL (10,2) NOT NULL,
	FK_COD_CLI INT NOT NULL
)

GO
/* ALTER TABLE'S */
ALTER TABLE VENDAS ADD CONSTRAINT PK_COD_VEN
PRIMARY KEY (COD_VEN)
GO
ALTER TABLE VENDAS ADD CONSTRAINT FK_VEN_CLI
FOREIGN KEY (FK_COD_CLI)
REFERENCES CLIENTES(COD_CLI)

GO

/*(EXERCÍCIO 3) SELECT COUNT(*) FROM VENDAS V
				INNER JOIN CLIENTES C
				ON C.COD_CLI = V.FK_COD_CLI
				WHERE (YEAR(DATA_VEN) = '2020')
				GROUP BY C.COD_CLI
*/

--- (EXERCÍCIO 4) SELECT SUM(TOTAL) FROM VENDAS

----------------------------------------------------------------------

CREATE TABLE ITENS_VENDA(
	QUANTIDADE INT NOT NULL,
	SUB_TOTAL DECIMAL (10,2) NOT NULL,
	FK_COD_VEN INT NOT NULL,
	FK_COD_PRO INT NOT NULL
)

GO
/* ALTER TABLE'S */
ALTER TABLE ITENS_VENDA ADD CONSTRAINT FK_IVE_VEN 
FOREIGN KEY (FK_COD_VEN)
REFERENCES VENDAS(COD_VEN)
GO
ALTER TABLE ITENS_VENDA ADD CONSTRAINT FK_IVE_PRO 
FOREIGN KEY (FK_COD_PRO)
REFERENCES PRODUTOS(COD_PRO)

GO
